name: CI/CD Pipeline

on: [push]

jobs:
  # Test and Build Job
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: |
          pnpm test

      - name: Build packages
        run: pnpm build

      - name: Check build outputs
        run: |
          ls -la packages/*/dist/
          echo "Build completed successfully"

  # Publish Stable Release (master branch)
  publish-stable:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Remove problematic .npmrc
        run: rm -f .npmrc

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Configure npm registry for publishing
        run: |
          echo "@amir-kaman:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish packages
        run: |
          # Publish tokens package
          cd packages/tokens
          cp package.json dist/package.json
          npm publish dist --tag latest
          cd ../..

          # Publish core package
          cd packages/core
          # Create a clean package.json for publishing
          cp package.json package.json.backup
          # Replace workspace dependency with actual version from tokens package
          TOKENS_VERSION=$(node -p "require('./packages/tokens/package.json').version")
          sed -i.bak "s/\"@amir-kaman\/sharmin-tokens\": \"workspace:\*\"/\"@amir-kaman\/sharmin-tokens\": \"^$TOKENS_VERSION\"/" package.json
          cp package.json dist/package.json
          npm publish dist --tag latest
          # Restore original package.json
          mv package.json.backup package.json
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Publish Prerelease (other branches)
  publish-prerelease:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Remove problematic .npmrc
        run: rm -f .npmrc

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Configure npm registry for publishing
        run: |
          echo "@amir-kaman:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish prerelease packages
        run: |
          run: |
          # Create timestamp-based prerelease version (matching your existing pattern)
          TIMESTAMP=$(date +%s)
          PRERELEASE_VERSION="0.0.1-${TIMESTAMP}.0"
          echo "Publishing prerelease version: $PRERELEASE_VERSION"

          # Publish tokens prerelease
          cd packages/tokens
          # Create a clean package.json for publishing
          cp package.json package.json.backup
          npm version $PRERELEASE_VERSION --no-git-tag-version
          mkdir -p dist
          cp package.json dist/package.json
          npm publish dist --tag prerelease
          # Restore original package.json
          mv package.json.backup package.json
          cd ../..

          # Publish core prerelease  
          cd packages/core
          # Create a clean package.json for publishing
          cp package.json package.json.backup
          # Replace workspace dependency with actual prerelease version
          sed -i.bak "s/\"@amir-kaman\/sharmin-tokens\": \"workspace:\*\"/\"@amir-kaman\/sharmin-tokens\": \"$PRERELEASE_VERSION\"/" package.json
          npm version $PRERELEASE_VERSION --no-git-tag-version
          mkdir -p dist
          cp package.json dist/package.json
          npm publish dist --tag prerelease
          # Restore original package.json
          mv package.json.backup package.json

          echo "✅ Published prerelease packages:"
          echo "📦 @amir-kaman/sharmin-tokens@$PRERELEASE_VERSION"
          echo "📦 @amir-kaman/sharmin-core@$PRERELEASE_VERSION"
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
